from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('solutions/', views.solutions, name='solutions'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.services, name='services'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/gantt-data/', views.dashboard_gantt_data, name='dashboard_gantt_data'),
    path('analytics/', views.analytics, name='analytics'),
    path('projects-page/', views.projects_page, name='projects_page'),
    path('projects/add/', views.add_project, name='add_project'),
    path('projects/edit/<int:project_id>/', views.edit_project, name='edit_project'),
    path('projects/delete/<int:project_id>/', views.delete_project, name='delete_project'),
    path('projects/<int:project_id>/details/', views.project_details, name='project_details'),
    path('projects/<int:project_id>/tasks/', views.project_tasks, name='project_tasks'),
    path('projects/<int:project_id>/send-report/', views.send_project_report, name='send_project_report'),
    path('projects/<int:project_id>/users/', views.get_project_users, name='get_project_users'),
    path('projects/<int:project_id>/assign-users/', views.assign_users_to_project, name='assign_users_to_project'),
    path('send-client-report/', views.send_client_report, name='send_client_report'),
    path('send-client-report-ajax/', views.send_client_report, name='send_client_report_ajax'),
    path('send-project-report/', views.send_project_report_ajax, name='send_project_report_ajax'),
    path('projects/add-task/', views.add_task, name='add_task'),
    path('projects/add-subtask/', views.add_subtask, name='add_subtask'),
    path('projects/toggle-subtask/', views.toggle_subtask, name='toggle_subtask'),
    path('projects/delete-task/', views.delete_task, name='delete_task'),
    path('projects/delete-subtask/', views.delete_subtask, name='delete_subtask'),
    path('projects/<int:project_id>/complete-task/<int:task_id>/', views.complete_task, name='complete_task'),
    path('projects/<int:project_id>/edit-task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('projects/<int:project_id>/edit-task/<int:task_id>/edit-subtask/<int:subtask_id>/', views.edit_subtask, name='edit_subtask'),
    path('settings/', views.settings, name='settings'),
    path('reports/', views.reports, name='reports'),
    path('send-report/', views.send_report, name='send_report'),
    path('send-complete-report/', views.send_complete_report, name='send_complete_report'),
    path('download-report/', views.download_report, name='download_report'),
    path('admin-control/', views.admin_control, name='admin_control'),
    
    # Admin endpoints
    path('admin-api/user/<int:user_id>/details/', views.admin_user_details, name='admin_user_details'),
    path('admin-api/user/<int:user_id>/permissions/', views.admin_user_details, name='admin_user_permissions'),
    
    path('logout/', views.logout_view, name='logout'),
    
    # Planner functionality - commented out until views are implemented
    path('planner/', views.user_planner, name='user_planner'),
    path('team-dashboard/', views.team_dashboard, name='team_dashboard'),
    # path('tasks/<int:task_id>/update/', views.update_task_status, name='update_task_status'),
    # path('tasks/<int:task_id>/update-with-notification/', views.update_task_with_notification, name='update_task_with_notification'),
    # path('tasks/<int:task_id>/extend/', views.extend_task_duration, name='extend_task_duration'),
    # path('tasks/<int:task_id>/comment/', views.add_task_comment, name='add_task_comment'),
    # path('subtasks/<int:subtask_id>/update/', views.update_subtask_status, name='update_subtask_status'),
    # path('subtasks/<int:subtask_id>/comment/', views.add_subtask_comment, name='add_subtask_comment'),
    # path('subtasks/<int:subtask_id>/extend/', views.extend_subtask_deadline, name='extend_subtask_deadline'),
    # path('notifications/enhanced/', views.admin_notifications_enhanced, name='admin_notifications_enhanced'),
    # path('notification-demo/', views.notification_demo, name='notification_demo'),
    # path('admin/respond/task-comment/<int:comment_id>/', views.admin_respond_to_task_comment, name='admin_respond_to_task_comment'),
    # path('admin/respond/subtask-comment/<int:comment_id>/', views.admin_respond_to_subtask_comment, name='admin_respond_to_subtask_comment'),
    # path('admin/send-message/', views.admin_send_message, name='admin_send_message'),
    # path('notifications/', views.get_notifications, name='get_notifications'),
    # path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    # path('notifications/<int:notification_id>/delete/', views.delete_notification, name='delete_notification'),
    # path('admin-notifications/', views.admin_notifications, name='admin_notifications'),
    path('system-logs/', views.system_logs, name='system_logs'),
    path('backup-management/', views.backup_management, name='backup_management'),
    path('backup-management/create/', views.create_backup, name='create_backup'),
    path('backup-management/upload/', views.upload_backup, name='upload_backup'),
    path('backup-management/restore/<int:backup_id>/', views.restore_backup, name='restore_backup'),
    path('backup-management/delete/<int:backup_id>/', views.delete_backup, name='delete_backup'),
    path('backup-management/download/<int:backup_id>/', views.download_backup, name='download_backup'),
    # path('system-monitoring/', views.system_monitoring, name='system_monitoring'),

    path('client/dashboard/', views.client_dashboard, name='client_dashboard'),
    path('client/settings/', views.client_settings, name='client_settings'),
    path('client/project/<int:project_id>/', views.client_project_detail, name='client_project_detail'),
    path('client/logout/', views.client_logout, name='client_logout'),
    path('client/setup-password/', views.client_setup_password, name='client_setup_password'),
    path('client/change-password/', views.client_change_password, name='client_change_password'),
    path('send-client-otp/', views.send_client_otp, name='send_client_otp'),
    
    # User password setup
    path('user/setup-password/', views.user_setup_password, name='user_setup_password'),
    path('user/reset-password/', views.user_reset_password, name='user_reset_password'),
    
    # AI Chatbot endpoints
    path('ai/chat/', views.ai_chat, name='ai_chat'),
    path('ai/feedback/', views.ai_feedback, name='ai_feedback'),
    path('ai/stats/', views.ai_stats, name='ai_stats'),
    path('ai/knowledge/', views.ai_knowledge_management, name='ai_knowledge_management'),
]