# Generated by Django 5.2.4 on 2025-08-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('in_progress_guidance_required', 'In Progress (Guidance Required)'), ('completed', 'Completed'), ('completed_review_pending', 'Completed (Review Pending)'), ('completed_data_discrepancy_addressing', 'Completed (Data Discrepancy addressing)')], default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('in_progress_guidance_required', 'In Progress (Guidance Required)'), ('completed', 'Completed'), ('completed_review_pending', 'Completed (Review Pending)'), ('completed_data_discrepancy_addressing', 'Completed (Data Discrepancy addressing)')], default='not_started', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('in_progress_guidance_required', 'In Progress (Guidance Required)'), ('completed', 'Completed'), ('completed_review_pending', 'Completed (Review Pending)'), ('completed_data_discrepancy_addressing', 'Completed (Data Discrepancy addressing)'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='not_started', max_length=50),
        ),
    ]
