# Generated by Django 5.1.7 on 2025-12-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='update_type',
            field=models.CharField(choices=[('completed', 'Completed'), ('delayed', 'Delayed'), ('on_hold', 'On Hold'), ('in_progress', 'In Progress'), ('in_progress_guidance_required', 'In Progress (Guidance Required)'), ('not_started', 'Not Started'), ('completed_review_pending', 'Completed (Review Pending)'), ('completed_data_discrepancy_addressing', 'Completed (Data Discrepancy Addressing)'), ('cancelled', 'Cancelled'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('deadline_extended', 'Deadline Extended'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned')], max_length=50),
        ),
    ]
