# Generated by Django 5.1.7 on 2025-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_taskupdate_update_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier', max_length=255)),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('satisfaction', 'Satisfaction Rating')], default='general', max_length=50)),
                ('feedback_text', models.TextField(blank=True, help_text="User's feedback message")),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], help_text='Satisfaction rating from 1-5', null=True)),
                ('user_email', models.EmailField(blank=True, help_text='User email if provided', max_length=254, null=True)),
                ('user_name', models.CharField(blank=True, help_text='User name if provided', max_length=200, null=True)),
                ('conversation_context', models.JSONField(blank=True, default=dict, help_text='Last few messages for context')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='User IP address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has feedback been addressed')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
            ],
            options={
                'verbose_name': 'Chatbot Feedback',
                'verbose_name_plural': 'Chatbot Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='home_chatbo_created_7c1418_idx'), models.Index(fields=['session_id'], name='home_chatbo_session_f129c1_idx'), models.Index(fields=['satisfaction_rating'], name='home_chatbo_satisfa_e0ad04_idx')],
            },
        ),
    ]
