# Generated by Django 5.1.7 on 2025-12-31 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chatbotfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('issue', 'Issue'), ('question', 'Question'), ('feedback', 'General Feedback')], default='feedback', help_text='Type of message', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject line', max_length=200)),
                ('message', models.TextField(help_text='Detailed message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Message priority', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Response from admin/dev')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When admin responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Related project if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_messages', to='home.project')),
                ('responded_by', models.ForeignKey(blank=True, help_text='Admin who responded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_message_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='dev_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dev Message',
                'verbose_name_plural': 'Dev Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='home_devmes_created_7abebf_idx'), models.Index(fields=['status'], name='home_devmes_status_974012_idx'), models.Index(fields=['message_type'], name='home_devmes_message_b657b6_idx'), models.Index(fields=['priority'], name='home_devmes_priorit_e0e795_idx')],
            },
        ),
    ]
