# Generated by Django 5.1.7 on 2026-01-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_devmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devmessage',
            name='subject',
            field=models.CharField(help_text='Brief subject line', max_length=1000),
        ),
    ]
